# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#
Listing.create(name: 'Copenhagen' )
Listing.create(name: 'Emanuel')
Listing.create(name: "Howell Barber")
Listing.create(name: "Hopper Lang")
Listing.create(name: "Stephanie Phelps")
Listing.create(name: "Hardy Greene")
Listing.create(name: "Carmen Gould")
Listing.create(name: "Crosby Fernandez")
Listing.create(name: "Lily Bass")
Listing.create(name: "Gladys Hull")
Listing.create(name: "Caitlin Mack")
Listing.create(name: "Terrie Maldonado")
Listing.create(name: "Olivia Shaw")
Listing.create(name: "Leblanc England")
Listing.create(name: "Ingrid Adams")
Listing.create(name: "Helen Willis")
Listing.create(name: "Vaughan Curry")
Listing.create(name: "Moses Pierce")
Listing.create(name: "Yvonne Cooley")
Listing.create(name: "Burks Small")
Listing.create(name: "Krista Pena")
Listing.create(name: "Alana Montoya")
Listing.create(name: "Durham Hinton")
Listing.create(name: "Patsy Johns")
Listing.create(name: "Beck Hoover")
Listing.create(name: "Cash Fisher")
Listing.create(name: "Aguirre Patel")
Listing.create(name: "Alisha Brennan")
Listing.create(name: "Preston Hendrix")
Listing.create(name: "Kate Fuller")
Listing.create(name: "Elnora Heath")
Listing.create(name: "Gay Wiley")
Listing.create(name: "Gilbert Cardenas")
Listing.create(name: "Kimberly Nguyen")
Listing.create(name: "Horn Hurst")
Listing.create(name: "Jillian Carroll")
Listing.create(name: "Combs Lynn")
Listing.create(name: "Mayer Fischer")
Listing.create(name: "Townsend Owens")
Listing.create(name: "Mcleod Rasmussen")
Listing.create(name: "Nona Todd")
Listing.create(name: "Boone Snow")
Listing.create(name: "Sally Trevino")
Listing.create(name: "Saundra Vazquez")
Listing.create(name: "Kathrine Walker")
Listing.create(name: "Barry Berg")
Listing.create(name: "Rosie Lott")
Listing.create(name: "Odonnell Carter")
Listing.create(name: "Catalina Daniels")
Listing.create(name: "Ballard Reed")
Listing.create(name: "Kerry Bean")
Listing.create(name: "Jacqueline Weber")
